# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Test

on:
  push:
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        node-version: [20.x, 22.x, 24.x, 26.x]

    steps:
    - uses: actions/checkout@v7
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v7
      with:
        node-version: ${{ matrix.node-version }}
        package-manager-cache: false

    # This project's .npmrc requires NPM 12. Upgrade NPM if possible,
    # or delete .npmrc.
    - name: Update npm or delete .npmrc
      run: |
        # Note: this check may cause spurious warnings about invalid npm
        # settings. npm 11 validates .npmrc even when you just run --version.
        if [ $(npm --version | sed 's/\..*//') -lt 12 ]; then
          if [ $(node --version | sed -e 's/\..*//' -e 's/^v//') -gt 20 ]; then
            npm install -g npm@latest
          else
            # NPM 12 won't run on Node 20.
            rm .npmrc
          fi
        fi

    - name: Report Node and NPM versions
      run: echo Using Node $(node --version) and NPM $(npm --version)

    - run: npm install
    - run: npm test
